### ISSUE TITLE
Could it be (in the debug mode) a feedback of the analysed elements?

### ISSUE THREAD

**Issue by Tyrben** [PurityWasHere/Fisherman#4]
It's hard to know why some states are not detected, Or why the state changes despite nothing moved on screen or on sound.

It would be nice to be able to see what the software sees.
Both the minigame zone, and the sound volume. To help calibrate it.

there are so many cases that can do the algorithm fail:
- the perspective
- the screen size
- multiple screens
- the OS screen zoom (ratio)
- the volume

PS: don't focus to much on baits, it should really be an option, not the default behaviour.

**Comment by LeandroLimaPRO** [comment]
#7 Remember to configure the parameters, since each machine works and has different variables!
