### ISSUE TITLE
I have a lot of problems with the bot

### ISSUE THREAD

**Issue by SupAnonymo** [PurityWasHere/Fisherman#8]
One of the main problems is the sound, the sound goes from 0-10000 without having made any sound, and when the bobber goes down, the bot does not even react.
I already tried downloading the bobbers and it doesn't work, I also tried to catch the fish and have the bot do the minigame but it just doesn't.
install all requirements without hassle, also uninstall and install VB Cable Audio

**Comment by LeandroLimaPRO** [comment]
check if the bot and the game are running on the same microphone drive (vb audio input)

**Comment by Noob654321** [comment]
how to check if both game and bot run on the same sound?
